### ISSUE TITLE
The solution does not builds

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/AzureAD-WebApp-GroupClaims-DotNet#58]
Hi team,
After downloading when i try to build the package in VS 2017 below error pops up

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.	WebApp-GroupClaims-DotNet	C:\MyProjects\DOTNET\Azure AD\active-directory-dotnet-webapp-groupclaims-master\active-directory-dotnet-webapp-groupclaims-master\WebApp-GroupClaims-DotNet\WebApp-GroupClaims-DotNet.csproj

And after that when i try to restore nuget packages below error comes up
![image](https://user-images.githubusercontent.com/11255054/70972479-89da0880-20f7-11ea-81b0-ef5790274925.png)

Please advise how to fix this.

**Comment by jmprieur** [comment]
@harry17preet 
did you clone the repo close to the root of the drive? I suspect you are hitting a long name issue on Windows.

I'd advise you clone by something like:
in C:\

```shell
git clone https://github.com/Azure-Samples/active-directory-dotnet-webapp-groupclaims groups
cd groups
```

**Comment by ghost** [comment]
Thanks a lot @jmprieur  . I overlooked the directory name which is a long name when cloning it.

**Comment by jmprieur** [comment]
Thanks for the update, @harry17preet !
